### ISSUE TITLE
Loading css-files

### ISSUE THREAD

**Issue by kalken** [jmfurlott/react-isomorphic-boilerplate#4]
I can't seem to be able to load css-files in this thing. Can someone give me a short example on how to do it and get every "path right".

my idea was to create a directory in src/shared/css with a main.css in it, and then use the webpack as:

```
  module: {
    loaders: [
      { test: /\.jsx?$/,
        loaders: ['react-hot', 'babel-loader'],
        exclude: /node_modules/,

      },
      { test: /\.css$/, loader: "style-loader!css-loader" }
```

However this does not work at all. doing something like

 import '../css/main.css';
in a file gives me some serious errors. I guess there are some paths on the different sides that does not work directly. And i can't figure out why...

I use my "import" css-path exactly as i use the js-paths. The js-path work fine but css does not work at all..

**Comment by Wolfeitz** [comment]
I keep mine in a css folder in the root.

In src/server/server.js, add this before the body tag
    style(type="text/css")
     include ../css/main.css

**Comment by jmfurlott** [comment]
There many different ways of doing it @kalken, actually haven't seen @Wolfeitz's before.  @Wolfeitz, what made you decide to that do that?

I actually do not use webpack for loading css files in isomorphic situations.  I prefer to build using the `node-sass` package from npm.  I fire up a parallel `node-sass -w` using npm scripts alongside starting my node and severs.  These three commands are called using the `&&` like on a CLI via `npm start` all in package.json!

**Comment by Wolfeitz** [comment]
I tried doing it within Jade - link(href='../css/main.css', rel='stylesheet') but that succeeded only in displaying the contents of the css file as text on the screen.
The include file worked as expected for me so I went with that one.  Working with Jade and React is all new to me to it's really just trial and error at this point.

**Comment by jmfurlott** [comment]
I'm not so sure that the `href` is right because to load the css via Jade it needs to be properly served as a static from Express.  

I think your syntax may be wrong @Wolfeitz. This has worked for me in other projects (be sure to put it in your head):

```
    link(rel="stylesheet" type="text/css" href="/css/style.css")
```

**Comment by jiv-e** [comment]
Hi! Thanks for your great tutorial @jmfurlott!

I would like to achieve something like this: http://bensmithett.com/smarter-css-builds-with-webpack/. The point is that I can import required styles on the component file se the dependencies are clear and everything stays modular. I got it to compile this: http://localhost:8080/js/app.css

But server side hangs and the http://localhost:3000 gives an error (connection refused). Here's the console output: https://gist.github.com/jiv-e/f9cdb11490e21c5e128e.

Any idea how to circumvent this? The problem seems to be that server.js doesn't find the css-file. Still it's compiled into app.css correctly, see the end of the console output.

I would greatly appreciate any guidance you could provide!
