### ISSUE TITLE
 Warning: No route matches path "/js/app.js". Make sure you have <Route path="/js/app.js"> 

### ISSUE THREAD

**Issue by monte-hayward** [jmfurlott/react-isomorphic-boilerplate#7]
Hi Joseph,
Thanks for the step-by-step post. I really learn a lot more creating from scratch than just cloning or forking as my starting point.

I did notice that the app described in your post throws a runtime error on first page load:

  `Warning: No route matches path "/js/app.js". Make sure you have <Route path="/js/app.js">  somewhere in your routes`

I went back through the code, and saw references to 'app.js' at two points, but no creation of app.js. Can you tell me the intent here, and what role app.js plays in the isomorphic application?
Thanks,
Monte

```
 index.jade
      script(src='http://localhost:8080/js/app.js', defer)


webpack.config.dev.js
output: {
    path: __dirname + '/public/js/',
    filename: 'app.js',
    publicPath: 'http://localhost:8080/js/',
},
```

I did not find an app.js in the repo:
`https://github.com/jmfurlott/react-isomorphic-boilerplate/search?utf8=%E2%9C%93&q=app.js`

**Comment by jmfurlott** [comment]
The `app.js` is the bundle that webpack is creating.  The development serve is generating that on change and outputting it at `/js/app.js`.  I am not sure what is specifically wrong with your without seeing it but what port is your Node server running on? I am guessing you got the `3000` and `8080` ports mixed it up as it _should not_ be looking for the bundle at `http://localhost:3000/js/app.js` which it apears to be, otherwise nothing could be triggering this warning.

**Comment by monte-hayward** [comment]
`16 Oct 12:44:29 - [nodemon] starting `node lib/server/server lib/server/server.js`
App listening at http://:::3000`

**Comment by monte-hayward** [comment]
At http://localhost:3000/   I see "Hello App Handler" as expected.
At 8080, I see an interestingly-styled browsable directory tree.

![screen shot 2015-10-16 at 1 34 53 pm](https://cloud.githubusercontent.com/assets/3780422/10550151/d7c7efe2-740a-11e5-8ff1-18fe62d2abdf.png)

**Comment by monte-hayward** [comment]
this was the diff
--mine
++yours
--script(src='/js/app.js', defer)
++script(src='htpp://localhost:8080/js/app.js', defer)

**Comment by jmfurlott** [comment]
Yep! Just crossed wires for a sec
